language: android

dist: trusty

jdk:
  - oraclejdk8

sudo: true

notifications:
  email: false

env:
  - SYS=21 ABI="default;armeabi-v7a"
  - SYS=24 ABI="google_apis;arm64-v8a"

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

android:
  components:
    - platform-tools
    - tools
#    - build-tools-27.0.3
#    - android-27
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19
#    - android-21
#    - sys-img-armeabi-v7a-android-21
#    - android-24
#    - sys-img-armeabi-v7a-android-24

before_install:
  # Install SDK license so Android Gradle plugin can install deps.
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" > "$ANDROID_HOME/licenses/android-sdk-license"
  - sdkmanager "system-images;android-$SYS;$ABI" > /dev/null
  - # Accept licenses before installing components, no need to echo y for each component
  - yes | sdkmanager "platforms;android-$SYS"
  - touch local.properties
  - chmod +x gradlew
  #  - echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a
  # Platform tools
  - sdkmanager "emulator" "tools" "platform-tools" > /dev/null
  - sdkmanager --list | head -15
  # install older build tools (for emulator)
  - sdkmanager "build-tools;25.0.2" "platforms;android-25" > /dev/null
  # Create and start emulator.
  - sdkmanager "system-images;android-$SYS;$ABI" > /dev/null
  - sdkmanager --list | head -15
  - echo no | avdmanager create avd -n test -k "system-images;android-$SYS;$ABI"
  # emulator debug options
  - EMU_DEBUG="-debug all -logcat *:e -verbose -show-kernel"
  - EMU_ADDITIONAL_OPTIONS="-camera-back none -camera-front none -memory 2048"
  - |
    if [[ "${SYS}${ABI}" == "25google_apis;armeabi-v7a" || "${SYS}${ABI}" == "24google_apis;armeabi-v7a" ]]; then
      EMU_PARAMS="-no-window -gpu swiftshader"
    else
      EMU_PARAMS="-no-boot-anim -gpu off"
    fi
    # use the absolute emulator path in case older version installed (on default path)
    $ANDROID_HOME/emulator/emulator -avd test -no-audio $EMU_PARAMS $EMU_ADDITIONAL_OPTIONS ${EMU_DEBUG} &

before_script:
  - ./scripts/android-wait-for-emulator.sh
#  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - ./gradlew clean check --parallel
  - ./gradlew detekt
  - ./gradlew connectedCheck

after_success:
  - .buildscript/deploy_snapshot.sh