language: android
jdk: oraclejdk8
sudo: false

notifications:
  email: false

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

branches:
  except:
    - gh-pages

env:
  global:
    - ADB_INSTALL_TIMEOUT=10
  matrix:
    - SYS=22 ABI="google_apis;armeabi-v7a"
    - SYS=24 ABI="google_apis;armeabi-v7a"

before_install:
  # Install SDK license so Android Gradle plugin can install deps.
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo "d56f5187479451eabf01fb78af6dfcb131a6481e" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" >> "$ANDROID_HOME/licenses/android-sdk-license"
  # Accept licenses before installing components, no need to echo y for each component
  - yes | sdkmanager "platforms;android-$SYS"
  # Install the rest of tools (e.g., avdmanager).
  - sdkmanager tools
  # Install the system image.
  - sdkmanager "system-images;android-$SYS;$ABI"
  # Create and start emulator for the script. Meant to race the install task.
  - echo no | avdmanager create avd --force -n test -k "system-images;android-$SYS;$ABI"
  - $ANDROID_HOME/emulator/emulator -avd test -no-audio -no-window &

install: ./gradlew clean assemble --stacktrace

before_script:
  - android-wait-for-emulator
  - adb shell settings put global window_animation_scale 0 &
  - adb shell settings put global transition_animation_scale 0 &
  - adb shell settings put global animator_duration_scale 0 &
  - adb shell input keyevent 82 &

script: ./gradlew check connectedCheck --stacktrace

after_success:
  - .buildscript/deploy_snapshot.sh